hero:
  xyz: "\"0.00  0.10 -0.60\""
  rpy: "\"0.00  0.00  0.00\""
infantry_CS004:
  xyz: "\"0.00  0.08  0.15\""
  rpy: "\"0.00  0.00  0.008\""
infantry_CS016:
  xyz: "\"0.00  0.13  0.05\""
  rpy: "\"0.00  0.00  0.00\""
sentry:
    # gimbal 2 camera
    gimbal2camera_xyz:        "\"0.0 0.0 0.0\""
    gimbal2camera_rpy:        "\"0.0 0.0 0.0\""
    gimbal2slave_camera_xyz:  "\"0.0 0.0 0.0\""
    gimbal2slave_camera_rpy:  "\"0.0 0.0 0.0\""
