/hik_camera_node:
  ros__parameters:
    camera_info_url: package://auto_aim/config/CS-016-old.yaml
    camera_frame: "camera_optical_frame" 
    camera_index: 0
    exposure_time: 4000.0
    gain: 16.77

/armor_detector_node:
  ros__parameters:
    model_path: opt-0527-001.onnx
    inference_driver: AUTO
    detect_color: BLUE

/custom_serial_node:
  ros__parameters:
    device_name: /dev/ttyACM0
    baud_rate: 115200
    flow_control: none
    parity: none
    stop_bits: "1"

/armor_tracker_node:
  ros__parameters:
    odom_frame: "odom"
    is_sentry: false
    ekf:
      #              x     vx     y   vy     z      vz     yaw   vyaw    r
      q_diagonal: [0.005, 0.01, 0.002, 0.001, 0.08, 0.005, 0.001, 0.001, 0.00001] # x vx y vy z vz yaw v_yaw r
      r_diagonal: [0.3, 0.25, 0.16, 0.04]  # x y z yaw
    tracker:
      max_match_distance: 0.5
      max_match_yaw: 1.0
      tracking_threshold: 5
      lost_threshold: 30