/master/hik_camera_node:
  ros__parameters:
    camera_info_url: package://auto_aim/config/CS-016-6mm-M.yaml
    camera_frame: "camera_optical_frame" 
    device_serial_number: "DA2849907"
    exposure_time: 4000.0
    gain: 16.98

/slave/hik_camera_node:
  ros__parameters:
    camera_info_url: package://auto_aim/config/CS-016-6mm-S.yaml
    camera_frame: "slave_camera_optical_frame"
    device_serial_number: "DA2849978"
    exposure_time: 4000.0
    gain: 16.98

/master/armor_detector_node:
  ros__parameters:
    model_path: "opt-0527-001.onnx"
    inference_driver: "CPU"
    detect_color: "BLUE"
    is_debug: true
    is_capture_raw_image: false
    is_capture_result_image: false

/slave/armor_detector_node:
  ros__parameters:
    model_path: "opt-0527-001.onnx"
    inference_driver: "GPU"
    detect_color: "BLUE"
    is_debug: true
    is_capture_raw_image: false
    is_capture_result_image: false

/master/armor_tracker_node:
  ros__parameters:
    odom_frame: "odom"
    is_debug: true
    ekf:
      #              x     vx     y   vy     z      vz     yaw   vyaw    r
      q_diagonal: [0.005, 0.01, 0.002, 0.001, 0.08, 0.005, 0.001, 0.001, 0.00001] # x vx y vy z vz yaw v_yaw r
      r_diagonal: [0.3, 0.25, 0.16, 0.04]  # x y z yaw
      s2qxyz: 0.28
      s2qyaw: 5.0
      s2qr: 80.0
      r_xyz_factor: 4e-4
      r_yaw: 5e-3
    tracker:
      max_match_distance: 0.5
      max_match_yaw: 1.0
      tracking_threshold: 5
      lost_threshold: 30

/slave/armor_tracker_node:
  ros__parameters:
    odom_frame: "slave_odom"
    is_debug: true
    ekf:
      #              x     vx     y   vy     z      vz     yaw   vyaw    r
      q_diagonal: [0.005, 0.01, 0.002, 0.001, 0.08, 0.005, 0.001, 0.001, 0.00001] # x vx y vy z vz yaw v_yaw r
      r_diagonal: [0.3, 0.25, 0.16, 0.04]  # x y z yaw
      s2qxyz: 0.28
      s2qyaw: 5.0
      s2qr: 80.0
      r_xyz_factor: 4e-4
      r_yaw: 5e-3
    tracker:
      max_match_distance: 1.5
      max_match_yaw: 1.0
      tracking_threshold: 5
      lost_threshold: 30

/controller_io_node:
  ros__parameters:
    color_notify: ["/master/armor_detector_node", "/slave/armor_detector_node"]
    master_tracker_topic: "/master/armor_tracker"
    slave_tracker_topic: "/slave/armor_tracker"

/custom_serial_node:
  ros__parameters:
    device_name: "/dev/ttyACM0"
    baud_rate: 115200
    flow_control: none
    parity: none
    stop_bits: "1"
