/hik_camera:
  ros__parameters:
    camera_name: narrow_stereo
    camera_info_url: package://auto_aim/config/CS-004.yaml
    camera_frame: "camera_optical_frame" 
    camera_index: 0
    exposure_time: 3000.0
    gain: 10.77
